#!/bin/bash
# Regenerate website/favicon.svg from the shipped app icon (brand/ask_the_page/icon-master.svg),
# then rasterize it into the favicon/logo/apple-touch-icon/PWA assets referenced by index.html
# and manifest.json.
# Usage: ./generate-icons.sh   (run from anywhere; paths resolve to website/)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WEB_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ROOT="$(cd "$WEB_DIR/.." && pwd)"
MASTER="$ROOT/brand/ask_the_page/icon-master.svg"
SVG="$WEB_DIR/favicon.svg"
ASSETS="$WEB_DIR/assets"

# favicon.svg is the store icon art under the 22% rounded mask the stores apply themselves.
python3 - "$MASTER" > "$SVG" <<'PY'
import pathlib
import sys

master = pathlib.Path(sys.argv[1]).read_text()
defs, body = master.split('</defs>', 1)
defs = defs.replace('aria-label="Scandora — Ask the Page"', 'aria-label="Scandora"').rstrip()
body = body.strip('\n').rsplit('</svg>', 1)[0].rstrip()
print('<!-- Generated by website/scripts/generate-icons.sh from brand/ask_the_page/icon-master.svg'
      ' — do not edit. -->')
print(defs)
print('    <clipPath id="squircle">')
print('      <rect width="1024" height="1024" rx="225" ry="225"/>')
print('    </clipPath>')
print('  </defs>')
print()
print('  <g clip-path="url(#squircle)">')
print(body)
print('  </g>')
print('</svg>')
PY

rsvg-convert -w 16 -h 16 "$SVG" -o "$ASSETS/favicon-16x16.png"
rsvg-convert -w 32 -h 32 "$SVG" -o "$ASSETS/favicon-32x32.png"
rsvg-convert -w 180 -h 180 "$SVG" -o "$ASSETS/apple-touch-icon.png"
rsvg-convert -w 512 -h 512 "$SVG" -o "$ASSETS/logo.png"

# PWA icons listed in website/manifest.json
for size in 72 96 128 144 152 192 384 512; do
  rsvg-convert -w "$size" -h "$size" "$SVG" -o "$ASSETS/icon-${size}x${size}.png"
done

ICO_TMP="$(mktemp -d)"
trap 'rm -rf "$ICO_TMP"' EXIT
rsvg-convert -w 16 -h 16 "$SVG" -o "$ICO_TMP/16.png"
rsvg-convert -w 32 -h 32 "$SVG" -o "$ICO_TMP/32.png"
rsvg-convert -w 48 -h 48 "$SVG" -o "$ICO_TMP/48.png"
magick "$ICO_TMP/16.png" "$ICO_TMP/32.png" "$ICO_TMP/48.png" "$WEB_DIR/favicon.ico"

# Social preview card — og-image.svg embeds assets/logo.png, so it restates the mark.
rsvg-convert -w 1200 -h 630 "$ASSETS/og-image.svg" -o "$ASSETS/og-image.png"
